CREATE TABLE Point
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    x        FLOAT                                   NOT NULL,
    y        FLOAT                                   NOT NULL,
    r        FLOAT                                   NOT NULL,
    hit_time TIMESTAMP WITHOUT TIME ZONE,
    hit      BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_point PRIMARY KEY (id)
);